# Generated by Django 5.0.14 on 2025-12-09 16:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_number', models.CharField(db_index=True, editable=False, max_length=15, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=20)),
                ('daily_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet_number'], name='wallet_wall_wallet__81edd0_idx'), models.Index(fields=['user', 'status'], name='wallet_wall_user_id_c4ebd1_idx')],
            },
        ),
    ]
