# Generated by Django 5.0.14 on 2025-12-11 01:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_data', models.JSONField(blank=True, default=dict)),
                ('sender_wallet_number', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient_wallet_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='wallet_tran_referen_f4b8af_idx'), models.Index(fields=['user', 'created_at'], name='wallet_tran_user_id_4e9914_idx'), models.Index(fields=['sender', 'created_at'], name='wallet_tran_sender__818085_idx'), models.Index(fields=['recipient', 'created_at'], name='wallet_tran_recipie_6ccca3_idx'), models.Index(fields=['status', 'created_at'], name='wallet_tran_status_58a2dc_idx'), models.Index(fields=['transaction_type', 'created_at'], name='wallet_tran_transac_7fcc7b_idx')],
            },
        ),
    ]
